mend pinktober logo
ae-utbm/sith3 pull request #481
Opened 2022-10-11 21:17 UTC by imperosol

2022-10-11 21:19 UTC, Juknum approved these changes

2022-10-11 21:23 UTC, Juknum commented
![image](https://user-images.githubusercontent.com/49886317/195201049-1c74c7bc-4e8a-4143-acfa-d3e57bdbee84.png)
Ce serait possible que la couleur du texte survolé soit la même que celle de l'ombre rose foncée?

2022-10-11 21:56 UTC, imperosol commented
> ![image](https://user-images.githubusercontent.com/49886317/195201049-1c74c7bc-4e8a-4143-acfa-d3e57bdbee84.png) Ce serait possible que la couleur du texte survolé soit la même que celle de l'ombre rose foncée?

Pas le but de la PR, j'ai juste remis le logo bien pour les utilisateurs non connectés.
Et en plus, rose sur rose, c'est illisible.

2022-10-12 05:55 UTC, TheoDurr requested changes

2022-10-12 05:55 UTC, TheoDurr commented on core/templates/core/base.jinja
>              <div id="header_connect_links">
Nan mais là on bouge le logo hors de la condition non ? Il a rien à faire là.

2022-10-12 06:47 UTC, merged