Updated 3DS to v2
ae-utbm/sith3 pull request #488
Opened 2022-11-12 13:53 UTC by TheoDurr

To Do before stage : 

- [x] Update model to record billing information
- [x] Update the call to the tpeweb
- [ ] Create a form to save billing information

Closes #479

2022-11-12 16:22 UTC, TheRolfFR approved these changes
Very good I must say, maybe some docstring for get_billing_info but really good overall

2022-11-12 17:20 UTC, imperosol requested changes
Pourquoi est-ce que la branche ne vient pas d'un checkout de master ? Là, je vois qu'elle est cinq commits derrière.

Les traductions des noms des champs du modèles n'ont pas été mises dans le fichier de trads.

Et aussi, il faut réécrire les tests, sinon ça passera jamais le pipeline.

2022-11-12 17:20 UTC, imperosol commented on eboutic/views.py
> +                    }
`{"totalQuantity": max(self.basket.items.count(), 99)}`

2022-11-13 09:25 UTC, TheoDurr commented on counter/models.py
> +
La relation OneToOne nous permet justement de pas s'embêter à créer un autre modèle. Personnellement je vois pas l'intérêt de séparer les deux. 

Cela me semble logique qu'un customer ait une adresse de facturation.

2022-11-13 13:15 UTC, imperosol commented on counter/models.py
> +
Sauf que là, on voit très clairement que toutes les informations de facturation font partie d'un sous-concept commun.
La relation OneToOne permet justement de faire de la composition, ce qui fait gagner : 
- en lisibilité : en séparant ce sous-comportement de la classe, on évite d'une part de réécrire `billing_` à chaque fois au début (je te jure que c'est lourd) et d'autre part on s'épargne une classe interminable avec une orgie de méthodes et un trop grand nombre de lignes
- ça fait qu'on gagne en maintenabilité, justement parce que c'est plus lisible et aussi parce que la séparation entre qu'est-ce qui se fait où est beaucoup plus claire. Et aussi, je te jure que c'est infiniment plus simple de gérer ça avec un ModelForm. Pour faire la même chose avec ce que tu as fait, ça serait vraiment chiant.
- On gagne en sécurité, parce que là, la db, elle est déjà pas mal remplie, donc pour rajouter ces putains d'infos, il faut soit mettre des valeurs par défaut (ce qui est absolument inenvisageable) soit mettre des champs null. Sauf que ces infos en question, la plupart sont obligatoires. NULL, c'est justement pour de l'optionnel. En fait, on utilise un concept pour ce qu'il n'est pas censé faire. Pire, comme certains champs (comme l'addresse 2) sont optionnels dans les informations de facturation, ça fait faire une distinction super chiante entre les champs null et ceux null-mais-pas-trop-en-fait, qui vont devoir être gérés différement alors qu'on les a déclaré pareil à la db. Et in fine, tu n'auras pas de garantie fiable que tout est rempli sans faire de suite horrible de if.

2022-11-13 14:46 UTC, Juknum commented on counter/models.py
> +
C'est bien sympa de critiquer et de proposer des solutions, mais se serait mieux d'apporter des modifs concrète à cette PR sans avoir à utiliser du passif agressif, c'est clairement pas sain. 

En outre j'ai aussi l'impression que tu oublies un peu ton rôle dans ce club. Le truc c'est que c'est de l'associatif, tu peux pas te permettre d'exiger des choses, surtout lorsqu'il t'as demandé en premier de l'aide. Critiquer c'est bien beau, ça renforce mentalement, mais apporter des commits avisés avec la méthodo que tu as suggéré, la ça renforce socialement & intellectuellement.

Donc soit tu amènes tes idées de façon concrète "eh regardez, ça c'est moyen faudrait faire comme ça" avec un commit qui suit pour corriger le tir : oui, là je valide avec validation. En revanche se permettre de lâcher un pavé en mode "oue c moi le boss en python/django, vous êtes nuls" c'est carrément non.

Je sens bien que tu veux faire avancer les choses, mais c'est contre-productif si tu t'exprimes comme ça.

2022-11-13 14:52 UTC, TheoDurr commented on counter/models.py
> +
> * On gagne en sécurité, parce que là, la db, elle est déjà pas mal remplie, donc pour rajouter ces **putains** d'infos, il faut soit mettre des valeurs par défaut (ce qui est absolument inenvisageable) soit mettre des champs null. 

D'autant plus que rajouter "putain" dans une demande de changement, alors que j'ai demandé explicitement ton aide, voilà.

2022-11-15 03:39 UTC, imperosol commented on counter/models.py
> +
Pour ce qui est de l'aide qu'on m'a demandé, j'y travaille actuellement. Malheureusement, il se trouve que ce n'est pas de l'ordre du trivial, parce que l'ajout que vous voulez faire s'insère dans le flux de la navigation avant le moment où les objets Customer sont créés. On n'est pas juste sur l'ajout d'un formulaire, deux vues et c'est plié, mais d'un peu plus que ça, mine de rien.

Quand à l'extrait de code, désolé si j'ai pu paraitre brutal, mais les faits sont là : c'est médiocre. Et là, ce n'est pas juste une mauvaise utilisation de Python ou de Django, c'est un problème de génie logiciel.

Mes idées, je les aies apportées de la manière la plus concrète possible. Je suis pas arrivé en gueulant "t'as fait que de la merde", j'ai expliqué le pourquoi du comment point par point. On me demande de faire un commit plutôt que de critiquer... Mais une review, c'est fait pour dire ce qui va et ce qui va pas, pas corriger le travail à la place de l'auteur.

2022-11-15 09:10 UTC, Hyask commented on eboutic/views.py
> +                        "totalQuantity": 99
You should probably precise in a comment that this value comes directly from the documentation and the protocol. A good idea when such hard-coded value must be used is to put it in a variable, such as `3DSV2_MAX_TOTAL_QUANTITY`, to show that you didn't choose this value arbitrarily, and hint future developer **not** to change it as they please.

2022-12-08 17:13 UTC, closed without merging