Repaired merge user feature
ae-utbm/sith3 pull request #498
Opened 2022-11-20 14:52 UTC by imperosol

J'ai réécrit la vue qui permettait de fusionner deux utilisateurs et écrit les tests associés.
Ca devrait résoudre tous ces problèmes qui étaient là :
- erreur quand un des deux utilisateurs n'a pas de compte pour les achats
- les groupes n'étaient pas fusionnés
- les fillots n'étaient pas fusionnés
- un utilisateur pouvait devenir son propre parrain
- perte de tout ou partie de la cotisation de l'utilisateur supprimé si l'utilisateur conservé est cotisant

Par contre, j'ai pas pu résoudre le problème de la non-fusion des images. Les images de profil de l'utilisateur resteront donc perdues. J'ai essayé de réparer, mais le problème vient de choix de conception atroces qui touchent au coeur même du site (je tiens à le redire, le concept même des SithFile était une connerie dès le début). Réparer ça nécessiterait des modifications en profondeur.

2022-11-21 11:33 UTC, Hyask commented
> Par contre, j'ai pas pu résoudre le problème de la non-fusion des images. Les images de profil de l'utilisateur resteront donc perdues. J'ai essayé de réparer, mais le problème vient de choix de conception atroces qui touchent au coeur même du site (je tiens à le redire, le concept même des SithFile était une connerie dès le début). Réparer ça nécessiterait des modifications en profondeur.

C'est quoi le problème de la non-fusion des images? Qu'est-ce qui empêche de mettre à jour le `OneToOne` `profile_pict`? C'est l'histoire du chemin dans lequel est stocké le fichier dessous qui se mettrait pas à jour tout seul qui te chagrine? Y'a la fonction `_repair_fs` pour ça, et même si tu la lances pas à chaque fois, c'est pas nécessairement un problème que ce soit mis à jour seulement par le `cron` une fois par semaine.  
Si le soucis, c'est d'avoir utilisé des `SithFile` pour la gestion des avatars, sache qu'en 2015, y'avait régulièrement des anciens qui contactaient l'AE pour demander de virer leurs photos qui étaient indexées par Google, et les avatars étaient compris dedans. C'est pour ça que maintenant ils ne sont pas fait simplement avec un `File` Django. Si maintenant c'est plus le cas et que vous décidez que les avatars seront publics, effectivement, ça simplifiera un peu le code.

J'ai pas retrouvé où tu avais expliqué les problèmes des SithFile, mais pour te donner un peu d'historique, ils ont permis de migrer l'existant sans soucis (l'ancien design est [là](https://github.com/ae-utbm/sith2/blob/master/include/entities/folder.inc.php) et [là](https://github.com/ae-utbm/sith2/blob/master/include/entities/files.inc.php)), de construire le SAS par dessus, ainsi que de servir aussi dans la compta, et manifestement ils fonctionnaient bien pour tout ça. Si les besoins ont changé, faut pas hésiter à mettre à jour, mais ça implémentait quand même tout le système de permissions nécessaire à l'époque.  
Aussi, si tu as une suggestion pour implémenter un système de fichier avec la gestion des permissions sans refaire une classe similaire, ça serait intéressant d'en discuter :-)

Enfin, je t'invite à un peu plus de bienveillance dans ton approche d'une base de code existante. "choix de conception atroces", "connerie", sont des jugements de valeur qui sont facile à faire quand on lit du code existant. On oublie souvent que le code n'a pas forcément été écrit juste par pur plaisir, mais souvent par besoin, et que l'ingénierie logicielle, c'est un processus extrêmement itératif. La conséquence, c'est qu'un design donné `n` ne satisfait jamais le besoin d'un design `n+1`, et donc qu'on est très souvent amené à râler sur le code existant parce qu'il ne remplit pas notre besoin du moment. Le problème de ça, c'est que tu te mets dans un état d'esprit assez négatif qui n'affecte au final que toi: les auteurs du code existant bien souvent ne sont plus là (et si ils sont là, ça va juste mener à te les mettre à dos, de leur râler dessus), des fois c'est ton toi du passé (donc c'est pire, tu te râle dessus tout seul!), et dans tous les cas, ça ne règle pas tes problèmes d'aujourd'hui, donc tu recommences demain, et ça s'empire.  
En conclusion, pour ton propre bien-être, il vaut généralement mieux approcher une base de code existante avec détachement, et éviter les jugements de valeurs hâtifs pour les remplacer par une vraie explication claire et précise de ce qui ne va pas, pour mieux définir le problème et le régler par la suite.

2022-11-21 17:54 UTC, klmp200 requested changes
Ça a l'air pas mal :)

2022-11-21 17:54 UTC, klmp200 commented on rootplace/views.py
> +            c_src.account_id = "UseIe55"
Je pense qu'utiliser un uuid ce serait mieux
Ici je peux voir un bug si jamais tu merge 2 users en même temps ce qui est pas impossible

2022-11-21 17:54 UTC, klmp200 commented on rootplace/views.py
>      def dispatch(self, request, *arg, **kwargs):
```suggestion
    def dispatch(self, request, *arg, **kwargs):
        if not request.user.is_root:
            raise PermissionDenied
        return super().dispatch(request, *arg, **kwargs)
```

2022-11-21 17:54 UTC, klmp200 commented on rootplace/views.py
> +        print(form.errors)
Attention au print sauvage

2022-11-23 09:19 UTC, imperosol commented on rootplace/views.py
>      def dispatch(self, request, *arg, **kwargs):
Bah, c'est déjà ce qu'il y a, en fait.

2022-11-23 09:20 UTC, imperosol commented on rootplace/views.py
> +        print(form.errors)
Je l'ai retiré

2022-11-23 09:20 UTC, imperosol commented on rootplace/views.py
>      def dispatch(self, request, *arg, **kwargs):
Bah, c'est déjà ce qu'il y a, en fait

2022-11-23 09:22 UTC, imperosol commented on rootplace/views.py
> +            c_src.account_id = "UseIe55"
La probabilité que deux utilisateurs soient fusionnés exactement en même temps est franchement négligeable.

2022-12-20 16:44 UTC, TheoDurr commented on rootplace/views.py
>      def dispatch(self, request, *arg, **kwargs):
@klmp200 tu confirmes que c'est bon pour toi ? Effectivement, ta suggestion est identique à ce qu'il y a déjà.

2023-01-11 21:20 UTC, imperosol commented
C'est bon, maintenant la méthode `Customer.get_or_create()` est passé sur taiste, je peux l'utiliser pour la touche finale de la réparation de l'outil de fusion des utilisateurs. Ca fait presque deux mois que Typhié l'avait demandé. Désolé Typhié.

2023-01-12 00:27 UTC, Juknum commented on rootplace/views.py
>      def dispatch(self, request, *arg, **kwargs):
@klmp200 up :eyes:

2023-03-03 12:57 UTC, TheoDurr approved these changes

2023-03-04 13:48 UTC, TheoDurr commented
@klmp200 Tu pourrais donner ta review étant donné que c'est toi qui a posé des commentaires ?

2023-03-04 14:01 UTC, merged