Unify account id creation
ae-utbm/sith3 pull request #499
Opened 2022-11-23 11:24 UTC by imperosol

Petite mise à jour qui répond au problème suivant : https://github.com/ae-utbm/sith3/issues/96

2022-12-15 16:21 UTC, imperosol commented
J'ai rajouté la touche finale, en suivant les conseils de Sli.
L'unification de la création de compte se fait par une méthode de classe `get_or_create` qui retourne le compte si celui-ci existe déjà, et sinon en crée un nouveau avec 0€ dessus et un identifiant unique.

Exemple : 
```py
user = User.objects.get(pk=<pk>)
account, created = Customer.get_or_create(user)
if created:
    print(f"Nouveau compte créé {account.id}")
else:
    print(f"{user} avait déjà un compte avec {account.id} € dessus"
```

J'ai aussi rajouté une valeur par défaut sur le champ `amount` du modèle `Customer`.
De manière assez amusante, il semblerait qu'un makemigration se soit perdu en chemin lors du travail sur les informations des facturation. Donc, par la force des choses, Django l'a mis dans le fichier de migration de cette PR.

2022-12-19 09:23 UTC, klmp200 requested changes
À part ça, c'est top !

2022-12-19 09:23 UTC, klmp200 commented on counter/models.py
> +    def get_or_create(cls, user: User) -> Tuple["Customer", bool]:
Avec `from __future__ import annotations` au tout début du fichier, tu peux utiliser Customer dans ton typing sans le mettre entre quotes

2022-12-19 12:07 UTC, imperosol commented on counter/models.py
> +    def get_or_create(cls, user: User) -> Tuple["Customer", bool]:
J'ai commit pour appliquer ça.

2022-12-20 09:17 UTC, klmp200 submitted a review, later dismissed

2022-12-20 16:35 UTC, TheoDurr requested changes

2022-12-20 16:35 UTC, TheoDurr commented on counter/migrations/0020_auto_20221215_1709.py
> +    ]
On effectue déjà cette migration dans #519 je crois

2022-12-20 16:35 UTC, TheoDurr commented on counter/tests.py
>  class AccountIdTest(TestCase):
Le nom est pas très clair, soit faudrait modifier le nom, soit y mettre un commentaire 👍🏻

2022-12-20 16:40 UTC, imperosol commented on counter/migrations/0020_auto_20221215_1709.py
> +    ]
Oui, c'est parce que comme j'en utilise certaines fonctionnalités, cette branche est basée sur l'autre.
![image](https://user-images.githubusercontent.com/56346771/208718955-eeb35e64-ec2d-4895-8d5b-8d32dae92f24.png)

On pourrait ne mettre en taiste que la #519 et retirer celle-là. Mais d'un autre côté, c'est peut-être mieux des les pousser l'une après l'autre pour tester ça graduellement.

2022-12-20 16:41 UTC, imperosol commented on counter/tests.py
>  class AccountIdTest(TestCase):
`CustomerAccountIdTest` ?

2023-01-08 14:33 UTC, imperosol commented
Tous les commits de la branche ont été squash.
La branche a été rebase sur le commit le plus récent de taiste.
Le fichier de migration a été un peu élagué pour s'assurer qu'il n'y ait pas de conflit avec la branche qui travaille sur les informations des facturation.

2023-01-09 20:43 UTC, imperosol commented
J'ai rebase sur la version de taiste qui vient d'être fusionnée avec master.

2023-01-10 15:39 UTC, klmp200 approved these changes

2023-01-11 12:26 UTC, merged