removed useless queries on counter stat
ae-utbm/sith3 pull request #519
Opened 2022-12-14 13:50 UTC by imperosol

Jusqu'à présent, la page des stats des comptoirs était très lente à charger (de l'ordre de 5 secondes en moyenne).
Le temps de chargement était pas tant dû la à la complexité des requêtes dans la vue qu'au nombre aberrant de requêtes qui se cachaient dans le template (500 requêtes plus pour des stats complètes).

Autre problème : la page n'était pas testable en local.

Cette PR règle les deux problèmes en reformulant les requêtes pour n'en laisser que 4 et rendre ça testable en local, pour le même résultat final.

La PR change aussi le style des tableaux pour les rendre un peu aérés et lisibles. Ca fait que concrètement, on passe de ça : 
![image](https://user-images.githubusercontent.com/56346771/207610264-7509d15f-6303-43a2-99f7-90c911948d42.png)
A ça : 
![image](https://user-images.githubusercontent.com/56346771/207610744-07cc6935-2cc7-4650-9a45-516963a55b27.png)

A noter que ce nouveau style de tableau est global. Sur le guide des UE, par exemple, ça donne ça 
![image](https://user-images.githubusercontent.com/56346771/207611106-b3bb4aa2-9ac8-48b7-a6f7-1b152aefa1c3.png)

Au cas où j'ai vérifié, mais c'est bon, ça ne nique pas le style des élections.

2022-12-14 18:12 UTC, Juknum requested changes
Ça à l'air pas mal, juste le fichier de trad qu'a pas été màj (3x rien) et est-ce que ça vaudrait pas le coup de faire des tests aussi?

2022-12-14 18:12 UTC, Juknum commented on counter/templates/counter/stats.jinja
> +            <td>{% trans %}N°{% endtrans %}</td>
C'est 3x rien, mais le fichier de trad à pas été mis à jour :o

2022-12-14 18:12 UTC, Juknum commented on counter/templates/counter/stats.jinja
> -                <td>{% trans %}Nb{% endtrans %}</td>
Tout pareil ici vis-à-vis du fichier de trad

2022-12-14 18:32 UTC, imperosol commented
> Ça donne quoi sur petit écran les tableaux? PS : si tu pouvais centrer verticalement le contenus des headers des tableaux aussi ça serait top :p

Ca donne ça.

![image](https://user-images.githubusercontent.com/56346771/207678808-8643b506-1c64-4142-84a4-7887afbe4aeb.png)

J'ai aussi rajouté le centrage vertical

2022-12-14 18:32 UTC, imperosol commented on counter/templates/counter/stats.jinja
> +            <td>{% trans %}N°{% endtrans %}</td>
En effet.
Comme c'est relativement international, je retire la trad pour ça.

2022-12-14 18:55 UTC, Juknum commented
> > Ça donne quoi sur petit écran les tableaux? PS : si tu pouvais centrer verticalement le contenus des headers des tableaux aussi ça serait top :p
> 
> Ca donne ça.
> 
> ![image](https://user-images.githubusercontent.com/56346771/207681299-fe388460-679b-45cf-ba6d-048f8fa05115.png)
> 
> J'ai aussi rajouté le centrage vertical

Et sur téléphone ? :eyes:

2022-12-15 00:58 UTC, imperosol commented
> > > Ça donne quoi sur petit écran les tableaux? PS : si tu pouvais centrer verticalement le contenus des headers des tableaux aussi ça serait top :p
> > 
> > 
> > Ca donne ça.
> > ![image](https://user-images.githubusercontent.com/56346771/207681299-fe388460-679b-45cf-ba6d-048f8fa05115.png)
> > J'ai aussi rajouté le centrage vertical
> 
> Et sur téléphone ? 👀

Mec, j'ai pas un serveur local sur mon tel, non plus. Je fais confiance à l'inspecteur de mon navigateur pour les dimensions d'un écran de téléphone.

2022-12-15 01:06 UTC, Juknum commented
> Mec, j'ai pas un serveur local sur mon tel, non plus. Je fais confiance à l'inspecteur de mon navigateur pour les dimensions d'un écran de téléphone.

Je fais pareil tqt hein xd, je trouvais ça juste un peu large pour du téléphone mdrr

2022-12-15 09:51 UTC, klmp200 approved these changes
C'est cool
J'ai lu les requêtes mais c'est difficile à suivre
Vu que c'est pas trop impactant si ça pète en prod, je te fait confiance :)

2022-12-15 23:22 UTC, TheoDurr reviewed
Manque plus que les tests et ça sera 👍🏻

2022-12-16 01:27 UTC, imperosol commented
J'ai rajouté les tests. Par contre, comme j'y utilise dedans la méthode `Customer.get_or_create` qui a été introduite la branche [unify-account-creation](https://github.com/ae-utbm/sith3/tree/unify-account-creation), j'ai rebase dessus.

La fusion de l'autre branche est donc souhaitable avant de fusionner celle ci.

2022-12-16 01:31 UTC, imperosol commented
Et je sais pas d'où sort le reformatage du dossier style.scss. J'ai pas souvenir de l'avoir reformaté.

2022-12-19 02:19 UTC, imperosol commented
Les millisecondes ont été tronquées.
La promo des barmen est maintenant indiquée.

![image](https://user-images.githubusercontent.com/56346771/208335131-63a277df-6000-4f3a-98fc-6f200bf250ae.png)

2022-12-20 12:28 UTC, Juknum submitted a review, later dismissed

2022-12-20 12:28 UTC, Juknum commented on counter/models.py
> +    def get_or_create(cls, user: User) -> Tuple["Customer", bool]:
Faudra mettre à jour avec la branche [unify-account-creation](https://github.com/ae-utbm/sith3/tree/unify-account-creation) avec ce commit https://github.com/ae-utbm/sith3/pull/499/commits/9de75f6279098c565e9bbfa047f80bb55ea99cb4

2022-12-20 13:51 UTC, imperosol commented on counter/models.py
> +    def get_or_create(cls, user: User) -> Tuple["Customer", bool]:
En effet. Je corrige ça 👍

2022-12-20 16:29 UTC, TheoDurr reviewed
Ca serait top si la date pouvait être en anglais et français 👍🏻

2023-01-08 17:17 UTC, imperosol commented
J'ai squash les anciens commits et j'ai rajouté la traduction pour les temps de permanences
![image](https://user-images.githubusercontent.com/56346771/211209755-9b9086cc-1850-41e4-82b8-9a66ab3554f3.png)

2023-01-08 20:22 UTC, Juknum approved these changes

2023-01-09 20:52 UTC, imperosol commented
J'ai squash les derniers commits. A part ça, pas de modifications.

2023-01-10 10:36 UTC, Juknum approved these changes

2023-01-10 10:37 UTC, Juknum commented
Vérifier que #533 fonctionne proprement avant de merge celle-ci :eyes:

2023-01-10 16:10 UTC, klmp200 commented
Je regarde pour un approval une fois que https://github.com/ae-utbm/sith3/pull/499 est mergé parce que ça dépend de ces changements :)

2023-01-11 22:17 UTC, imperosol commented
J'ai résolu un merge conflict

2023-03-03 12:56 UTC, TheoDurr submitted a review, later dismissed

2023-03-06 13:18 UTC, Juknum approved these changes

2023-03-07 23:24 UTC, imperosol commented
wtf, les tests de la galaxie échouent alors que j'y ai touché ni de près ni de loin. J'ai essayé de faire tourner les tests sur master avec une bse de données regénérée et ils échouent aussi. Je vois pas d'où ça peut venir.

2023-03-08 19:32 UTC, imperosol commented
J'ai rebase la PR. Ca devrait être prêt à partir en taiste, une fois que taiste sera parti en prod.

2023-03-08 20:05 UTC, TheoDurr commented
Au niveau du tableau des cotisations, j'ai un petit soucis graphique : (testé sur Chrome, Safari et Firefox)

![CleanShot 2023-03-08 at 21 03 49](https://user-images.githubusercontent.com/47631598/223835286-f3fc7b1d-44cd-46e8-80cd-24c28eee7bff.png)

L'animation de déroulement est assez laggy aussi

2023-03-09 10:29 UTC, imperosol commented
Ca devrait être un peu mieux 
![image](https://user-images.githubusercontent.com/56346771/223997016-e6cfda05-0a0d-46cd-9fb2-27e81dcf1fdd.png)

2023-03-12 10:31 UTC, imperosol commented
J'ai rebase parce qu'il y avait un conflit au niveau des locales

2023-03-24 14:31 UTC, TheoDurr approved these changes

2023-03-24 14:32 UTC, merged