redirect the user directly on counter if user is barman
ae-utbm/sith3 pull request #530
Opened 2022-12-17 15:51 UTC by imperosol

C'est très chiant de devoir modifier manuellement son URL pour arriver sur la page du comptoir, particulièrement sur téléphone (et justement, les comptoirs sont beaucoup utilisés sur tel).

Donc ici, on fait en sorte que quand on clique sur un comptoir dans le bandeau supérieur, on redirige l'utilisateur :
- s'il est barman du comptoir en question : vers la page du comptoir (sans qu'il ait à modifier manuellement l'URL)
- sinon, vers la page d'activité du comptoire (comme avant)

Pour faire ça sans rajouter de requêtes supplémentaire, j'ai modifié le Manager par défaut du modèle `Counter` afin de lui rajouter la méthode `annotate_user_is_barman(user)`, qui permet d'annoter le queryset avec un booléen qui vaut True quand l'utilisateur fait partie des vendeurs du comptoir en question, sinon False.

2022-12-19 09:17 UTC, klmp200 requested changes
À part ça c'est cool :)

2022-12-19 09:17 UTC, klmp200 commented on counter/models.py
> +        return self.annotate(user_is_barman=Exists(subquery))
Je propose un meilleur nom pour ça
```suggestion
        return self.annotate(is_current_user_barman=Exists(subquery))
```

2022-12-19 09:17 UTC, klmp200 commented on counter/tests.py
> +            if counter.name in ("Foyer", "MDE"):
Pourquoi que Foyer et MDE ? Il y a la gomette aussi :P
Normalement, ça devrait être vrai pour tous les counter définis comme des bars physiques :)

2022-12-19 09:17 UTC, klmp200 commented on counter/tests.py
> +            if counter.name in ("Foyer", "MDE"):
```suggestion
            self.assertEqual(counter.is_current_user_barmen, counter.name in ("Foyer", "MDE"))
```

2022-12-19 11:50 UTC, imperosol commented on counter/tests.py
> +            if counter.name in ("Foyer", "MDE"):
Pourquoi que Foyer et MDE ? Parce que l'utilisateur testé, il fait partie des barmen du Foyer et de la MDE, mais pas de ceux de la Gomette. Si jamais la fonction déclare qu'il fait partie de comptoirs auxquels ont ne l'a pas ajouté, ça serait problématique.

2022-12-19 12:02 UTC, imperosol commented on counter/tests.py
> +            if counter.name in ("Foyer", "MDE"):
Joli, mais c'est pas très lisible.

2022-12-19 12:03 UTC, imperosol commented on counter/models.py
> +        return self.annotate(user_is_barman=Exists(subquery))
On en a parlé, mais du coup non, ça décrit pas le comportement du queryset.

2022-12-20 16:39 UTC, TheoDurr commented on core/templates/core/base.jinja
> +                                {% endif %}
Je pense que les codes héxa auraient plus leur place dans le SCSS.

2022-12-20 16:39 UTC, TheoDurr commented on counter/tests.py
> +    def test_custom_queryset(self):
C'est bien de faire un mini commentaire à chaque fois pour expliquer le but du test 👍🏻

2022-12-20 16:46 UTC, imperosol commented on core/templates/core/base.jinja
> +                                {% endif %}
Pour le coup, ça c'est quelque chose qui était déjà là. La seule chose que j'ai changé sur ces lignes, c'est l'indentation.
Et je me dis que dans la mesure où ce sont des couleurs qui sont utilisées à un seul endroit, c'est pas déconnant qu'elles soient en dur dans l'html ; du moins pour l'instant.

2022-12-20 16:48 UTC, imperosol commented on counter/tests.py
> +    def test_custom_queryset(self):
Je rajoute ça.

2023-01-10 16:06 UTC, klmp200 commented on counter/models.py
> +    def annotate_is_barman(self, user: User) -> "CounterQuerySet":
On s'est mis d'accord sur annotate_has_barman(user).has_annotated_barman

2023-01-10 16:17 UTC, klmp200 approved these changes

2023-01-10 16:38 UTC, imperosol commented
J'ai squash les commits

2023-01-10 18:01 UTC, klmp200 approved these changes

2023-01-11 22:24 UTC, merged