[CSS] Amélioration des pages utilisateurs pour les petits écrans
ae-utbm/sith3 pull request #578
Opened 2023-03-03 11:29 UTC by Juknum

Ancienne PR: https://github.com/ae-utbm/sith3/pull/576
Comme le rebase était assez chiant, j'ai refais la PR directement sur `taiste`

## Page d'infos
<details><summary>Screens</summary>
<p align="center">
<img src="https://user-images.githubusercontent.com/49886317/222599696-e1f36bba-d9a8-4665-b441-8169e9ac5afd.png "/>
<img width="390" src="https://user-images.githubusercontent.com/49886317/222599782-5f693d15-9e6a-44ed-ade4-5f9455dcf29d.png" />
<img width="390" src="https://user-images.githubusercontent.com/49886317/222599806-cf7644cd-a125-4c7a-90a4-7003e87743d7.png" />
</p>
</details>

## Page des outils 
(j'ai viré les douze milles `<hr/>`)
<details><summary>Screens</summary>
<img src="https://user-images.githubusercontent.com/49886317/222600244-d2bb1ad2-90d7-4c54-86ec-a0aafe001940.png">
</details>

## Page d'édition d'un profil
<details><summary>Screens</summary>
<p align="center">
<img src="https://user-images.githubusercontent.com/49886317/222600569-4e00756c-3b49-4505-9bf3-cdee6a4adfe4.png "/>
<img width="390" src="https://user-images.githubusercontent.com/49886317/222600589-6b86d750-e0a5-40a7-b25f-850ae93044e5.png" />
<img width="390" src="https://user-images.githubusercontent.com/49886317/222600649-d14a1005-6160-4218-8d93-b201bbfbd03b.png" />
<img width="390" src="https://user-images.githubusercontent.com/49886317/222600685-69c34ed4-f0f3-4a64-b457-52dccf1dd368.png" />
</p>
</details>

## Page des préférences 
<details><summary>Screens</summary>
<p align="center">
<img src="https://user-images.githubusercontent.com/49886317/222600880-e807dd1c-1551-4ad9-a331-bd6a89611a0f.png"/>
<img width="390" src="https://user-images.githubusercontent.com/49886317/222600916-14462265-068d-466d-822c-be8c14c7e97e.png" />
</p>
</details>

## Page des stats
<details><summary>Screens</summary>
<p align="center">
<img src="https://user-images.githubusercontent.com/49886317/222601035-b11191df-af82-4adc-97ac-4ae367224a0f.png"/>
<img width="390" src="https://user-images.githubusercontent.com/49886317/222601065-0a6ca815-a92e-4cf2-a80c-73697e2ec15e.png" />
</p>
</details>

2023-03-03 12:40 UTC, TheoDurr submitted a review, later dismissed

2023-03-03 23:50 UTC, imperosol commented
Attention, la PR #575 a fait des modifications sur les feuilles de style. Il faudrait faire un merge de master dans taiste puis rebase.

2023-03-03 23:51 UTC, Juknum commented
> Attention, la PR #575 a fait des modifications sur les feuilles de style. Il faudrait faire un merge de master dans taiste puis rebase cette PR.

Les pages modifiées ont leurs CSS dans leurs propres fichiers donc zéros soucis

2023-03-04 22:42 UTC, imperosol reviewed
C'est super cool, à l'exception du fait que ça fait de l'héritage sans toucher aux propriétés qui s'appliquaient jusque là. Niveau maintenabilité, c'est vraiment pas terrible. Mieux vaut carrément extraire tout le style relatif aux utilisateurs de `style.scss` et éviter des duplications redondantes entre fichiers.

2023-03-06 13:11 UTC, Juknum commented on core/models.py
> +    quote = models.TextField(_("quote"), max_length=256, blank=True, default="")
Ça a été demandé par des gens de l'UTBM avec la raison suivante : "Je peux pas lire ma quote en entier, ça serait bien de pouvoir tout lire d'un coup".

Ça mange pas de pain du coup je l'ai mis 👍

2023-03-06 18:11 UTC, imperosol commented on core/static/core/override.scss
> +}
> Le problème avec le CSS du site 3, c'est que tout est dans un seul fichier, donc à part en vérifiant tous les endroits avec du HTML je peux pas être certains que le CSS que je modifie ne soit pas utilisé ailleurs, d'ou le fait que j'ai créé ce fichier pour éviter de casser des trucs ailleurs.

La recherche de symboles, c'est une des fonctionnalités de base d'un éditeur qui se respecte. Ca se fait assez bien, d'autant plus que ce à quoi tu touches, ce sont presque entièrement des id. Je suis prêt à parier que la plupart n'ont qu'un seul usage sur tout le site, ce qui rend leur extraction d'autant moins plus compliquée et d'autant plus pertinente.

Je suis d'accord que pour l'instant, ça n'est pas très maintenable, mais la solution à ça n'est sans doute pas de réduire encore la maintenabilité pour s'épargner quelques minutes de recherche.

2023-03-06 22:43 UTC, imperosol requested changes
Quelques remarques en plus.

Par contre, il faudrait purger `style.scss` des lignes [1300 à 1380](https://github.com/ae-utbm/sith3/blob/b7f20fed6c89eb69f5ae8e163115535e35690ead/core/static/core/style.scss#L1300) pour que le style de cette partie se fasse entièrement là où il doit se faire. Ca permettra aussi de retirer les `!important` qui sont trop nombreux.

2023-03-07 12:20 UTC, Juknum commented on core/static/core/override.scss
> +}
ça devait être :
```scss
#content {
  padding: 20px !important;
}
```
mais après avoir corrigé de mon côté, ça fait un décalage entre les pages que j'ai retouchée et celle qui sont restées intactes, donc ça va juste gicler.

2023-03-08 01:15 UTC, Juknum commented
## SAS
<details><summary>Screens</summary>
<p align="center">
<img src="https://user-images.githubusercontent.com/49886317/223592882-08722678-05c4-49c0-8e17-67ea4605d855.png">
<img src="https://user-images.githubusercontent.com/49886317/223592963-8989698b-5425-4d52-b9bc-97bb37999f31.png">
</p>
</details>

## SAS (dans un album)
Les photos à modérer sont floutées.

<details><summary>Screens</summary>
<p align="center">
<img src="https://user-images.githubusercontent.com/49886317/223593123-c6e4584c-a623-4dfd-8219-fd2f940908f5.png">
<img src="https://user-images.githubusercontent.com/49886317/223593197-49e17268-7011-4962-be77-a96f39811b25.png">
<img src="https://user-images.githubusercontent.com/49886317/223593375-e076ffab-c3fc-499b-ab70-f2b5d7bde3e1.png">
<img src="https://user-images.githubusercontent.com/49886317/223593405-3b017cbf-d1bd-4b1a-b5d8-722fa94df90b.png">

</p>

### Bugs que j'ai remarqué : 
- On peut pas supprimer un album à la racine du SAS
- Tourner une image vers la droite/gauche ne fonctionne pas correctement

2023-03-13 13:12 UTC, Juknum commented
> Je maintiens la remarque que j'ai faite sur la migration de la db qui n'est pas nécessaire et dont le changement apporté devrait être fait dans les formulaires, pas dans les modèles.

Ça change vraiment rien, si le modèle est un champ long, autant que la base de donnée le soit. De plus, la taille du champs ne change pas. Si jamais dit moi ou ça se trouve.

> Egalement, il faudrait nettoyer style.scss, qui contient maintenant énormément de code mort et de code propre à un id unique qui devient alors plus dur à surcharger ailleurs et nécessite une quantité excessive de `!important`.

Le problème avec `style.scss` c'est que je peux pas savoir avec précision ou c'est utilisé dans le projet. D'ailleurs la plupart du temps je ne fais que le surcharger, du coup c'est très chiant de savoir s'il faut, ou non, enlever le code initial dans le fichier.

> Ce sont mes premières remarques. Je n'ai pas le temps dans l'immédiat de lire ça dans la totalité des détails, donc je me limite pour l'instant à ces deux principaux points.

J'ai update la description de la PR avec les dernières modifs (avec des screenshots et tout et tout)

2023-03-14 11:24 UTC, imperosol commented
T'as oublié de black

2023-03-14 12:06 UTC, Juknum commented
Yes effectivement c'est pas mal

2023-03-14 13:59 UTC, imperosol reviewed
L'ombre sur le popup des notifications n'est pas très belle :
![image](https://user-images.githubusercontent.com/56346771/225020728-9067ffbf-514f-4d7d-8c35-737587062da6.png)

Toute la partie de style.scss du header jusqu'a `#popupheader`. `#header_language_chooser` est du code mort et `header` devrait être surchargé proprement. Pareil pour `#user_profile_page` et toute la partie du SAS. Au total, ça fait environ 300 lignes qu'on peut retirer de style.scss, plus les lignes que ça va retirer de ton style étant donné qu'il n'y aura plus de style de base à surcharger.

Si tu as peur que ça détruise quelque chose autre part, il faut faire `ctrl maj F` et regarder.

`navbar.scss` devrait s'appeler `header.scss`.

Toutes les feuilles de style du SAS devraient être déplacées dans la bonne application.

2023-03-14 13:59 UTC, imperosol commented on core/templates/core/user_pictures.jinja
> +    <div class="main">
```suggestion
    <main>
```

Ou bien `main id=page-main`

Et tu utilises ça dans pas mal de templates, donc incorpore-le plutôt à base.jinja

2023-03-14 13:59 UTC, imperosol commented on core/templates/core/user_stats.jinja
> +        </div>
Pourquoi changer cette partie ?

2023-03-14 13:59 UTC, imperosol commented on core/templates/core/user_tools.jinja
> +        {% endfor %}
Toute la base de code est en snake_case. Evite d'utiliser une autre convention de nommage.

2023-03-14 13:59 UTC, imperosol commented on core/utils.py
> +        .decode("ascii")
```suggestion
        .decode()
```

2023-03-14 13:59 UTC, imperosol commented on locale/fr/LC_MESSAGES/django.po
> +msgstr "Site réalisé par le Pôle Informatique de l'AE"
J'aurais dit "Site réalisé par et pour les étudiants de l'AE".
Simple préférence personnelle.

2023-03-14 13:59 UTC, imperosol commented on sas/templates/sas/album.jinja
> +    {% endif %}
```suggestion
    {% if file and file.parent %}
        {{ print_path(file.parent) }}
        <a href="{{ url('sas:album', album_id=file.id) }}">{{ file.get_display_name() }}</a>
    {% endif %}
```

2023-03-14 13:59 UTC, imperosol commented on sas/templates/sas/main.jinja
> +        {% else %}
Si ça concerne toute la vue, pas de gestion de l'autentification dans le template. Ici, la gestion de l'authentification et des autorisations doit se faire dans la vue.

2023-03-14 13:59 UTC, imperosol commented on core/templates/core/base.jinja
> +                        <a class="header-logo-picture" href="{{ url('core:index') }}" style="background-image: url('{{ static('core/img/logo_no_text.png') }}')">
Utilise des id plutôt que des classes, ici. C'est plus pratique niveau sémantiques et ça diminue après coup le risque de détruire par accident le style du header avec une mauvaise surcharge.

Pour l'id du header, utilise aussi une appelation plus précise pour qu'on comprenne bien de quoi il s'agit : du genre `main-header` ou `page-header` ou `top-header`

2023-03-14 13:59 UTC, imperosol commented on core/templates/core/base.jinja
> +                                            {% if  user.notifications.filter(viewed=False).count() < 100 %}
Tu fais une requête de trop (et même plus quand on regarde les requêtes qui sont faites après)
Et pourquoi mettre la condition `< 100` ?

2023-03-14 13:59 UTC, imperosol commented on core/templates/core/base.jinja
> +                                        <ul>
Ca va surtout concerner le CSS, mais essaie d'augmenter la hauteur minimale allouée aux notifications, pour éviter d'afficher la barre de défilement quand c'est pas nécessaire
![image](https://user-images.githubusercontent.com/56346771/225019490-b420a0a4-5d1b-4adf-b2d8-f2c991cdfb95.png)

2023-03-14 14:04 UTC, Juknum commented on sas/templates/sas/main.jinja
> +        {% else %}
Je sais pas comment les droits ont été fait, mais sache qu'a l'heure actuelle tu peux te rendre sur le SAS en étant déconnecté, cependant les photos ne chargeront pas car l'utilisateur déconnecté n'as pas les droits d'accès aux dites photos (logique)

2023-03-14 14:05 UTC, Juknum commented on sas/templates/sas/album.jinja
> +    {% endif %}
Bah non ? C'est pour afficher le chemin complet du fichier ? genre `machin / truc / ici / fichier.log`

2023-03-14 14:09 UTC, imperosol commented on core/templates/core/base.jinja
> +                                            {% if  user.notifications.filter(viewed=False).count() < 100 %}
Pour ce genre de cas, c'est pas trop grave si ça bave. Du moins, je pense que c'est mieux d'avoir un affichage pas très beau que de juste avoir l'impression qu'on ne reçoit plus de notifications une fois la centième non lue dépassée.

2023-03-14 14:10 UTC, Juknum commented on core/templates/core/user_stats.jinja
> +        </div>
Fondamentalement, rien à changer. Les infos affichées sont toujours les mêmes, du coup je vois pas ce que tu dire ?

2023-03-14 14:12 UTC, imperosol commented on sas/templates/sas/album.jinja
> +    {% endif %}
Rahoui, autant pour moi.

2023-03-14 14:13 UTC, imperosol commented on core/templates/core/user_stats.jinja
> +        </div>
Je veux dire : pourquoi remplacer les balises `p` par beaucoup plus de balises qui n'ont pas de signification intrinsèque ?

2023-03-14 14:23 UTC, Juknum commented on core/templates/core/login.jinja
> +            <p class="danger">{% trans %}Your username and password didn't match. Please try again.{% endtrans %}</p>
C'était déjà comme ça

2023-03-14 14:25 UTC, imperosol commented
> > Je maintiens la remarque que j'ai faite sur la migration de la db qui n'est pas nécessaire et dont le changement apporté devrait être fait dans les formulaires, pas dans les modèles.
> 
> Ça change vraiment rien, si le modèle est un champ long, autant que la base de donnée le soit. De plus, la taille du champs ne change pas. Si jamais dit moi ou ça se trouve.

Pour expliquer d'où peut venir le problème : [https://forum.djangoproject.com/t/textfield-or-charfield/11432](https://forum.djangoproject.com/t/textfield-or-charfield/11432)

Pour l'instant, on a beaucoup de chances, parce que tout s'agence bien pour qu'au final ça ne change rien (même performance de VARCHAR et TEXT dans Postgre, bonne conception des formulaires Django), mais on retire tout de même une protection accordée par les contraintes de la DB. Si on vient à modifier le formulaire où à utiliser ce champ dans un mauvais contexte, ça pourrait créer une faille.

C'est justement pour ça que de manière générale, si on veut apporter un changement purement visuel, c'est aux vues, aux formulaires et aux templates qu'il faut toucher, pas aux modèles.

2023-03-14 14:26 UTC, Juknum commented on core/templates/core/user_stats.jinja
> +        </div>
Ça permet de séparer en deux groupe & d'utiliser le CSS ci-dessous pour aligner et espacer les éléments (ici le texte) simplement, sans utiliser de tableau.

```css
display: flex;
flex-direction: column;
justify-content: space-between;
```

2023-03-14 14:27 UTC, Juknum commented on core/templates/core/user_tools.jinja
> +        {% endfor %}
my bad

2023-03-14 14:28 UTC, imperosol commented on core/templates/core/login.jinja
> +            <p class="danger">{% trans %}Your username and password didn't match. Please try again.{% endtrans %}</p>
En effet, autant pour moi

2023-03-14 14:29 UTC, imperosol commented on core/templates/core/user_stats.jinja
> +        </div>
Ok 👍

2023-03-14 14:32 UTC, Juknum commented on core/templates/core/base.jinja
> +                                            {% if  user.notifications.filter(viewed=False).count() < 100 %}
Bah si justement, le but c'est d'éviter que ça bave. En plus, le nombre de personne qui dépasse les 100 notifications sont assez peu fréquent, et en général ils se moque éperdument du nombre de notif qu'ils ont lorsque ça dépasse ce nombre, sinon, ils auraient "marqués les notifications comme lues"

2023-03-14 14:38 UTC, imperosol commented on core/templates/core/base.jinja
> +                                            {% if  user.notifications.filter(viewed=False).count() < 100 %}
Même en étant dans ce genre de cas, je considèrerai ça plus comme un bug que comme une fonctionnalité.
Avec des notifications à trois chiffres, ça ressemble à ça : 
![image](https://user-images.githubusercontent.com/56346771/225035607-395615fb-2446-4d11-838a-ac563854a2a3.png)

Clairement, on peut pas dire que ça soit si moche que ça.

Et si tu veux vraiment que ça ne déborde jamais, alors un système à la discord est sans doute préférable 
![image](https://user-images.githubusercontent.com/56346771/225035940-fa04fd90-67e5-4ad5-93d8-74dc9c41bdc4.png)

2023-03-14 14:43 UTC, klmp200 commented on sas/templates/sas/main.jinja
> +        {% else %}
Les droits des images sont calculés quand un utilisateur tente d'accéder aux images, si tu vas sur le sas sans être connecté, tu ne verra que les images mises en publique parce que la requête de ton navigateur sur une image privée va te jeter

2023-03-14 14:48 UTC, Juknum commented on sas/templates/sas/main.jinja
> +        {% else %}
On le contrôle ou le niveau de visibilité d'une image du SAS ? quand j'ai upload des photos sur ma version de dev, à aucun moment j'ai du choisir si l'album ou les photos seraient privées / publiques 🤔

2023-03-14 15:29 UTC, imperosol commented on sas/templates/sas/main.jinja
> +        {% else %}
Ca se retrouve en fouillant dans le code source de sas/views.py. Il n'y a pas de gestion explicite des droits, mais c'est hardcodé pour bloquer les utilisateurs non-authentifiés, non-cotisants ou quand l'image n'a pas été modérée.

2023-03-15 07:44 UTC, Juknum commented on core/utils.py
> +        .decode("ascii")
Bah non du coup :

<img width="184" alt="Capture d’écran 2023-03-15 à 08 44 09" src="https://user-images.githubusercontent.com/49886317/225240786-8a845566-a23f-459e-ba6c-faf6be9070fb.png">

2023-03-15 10:58 UTC, imperosol commented
Il y a toujours le problème de la barre de défilement 
![Screenshot_20230315_115808](https://user-images.githubusercontent.com/56346771/225289300-cb0ade1a-1c4d-473c-b737-796afe5231fa.png)

2023-03-15 11:00 UTC, imperosol commented
Problème d'espacement sur le header des utilisateurs non-authentifiés : 
![Screenshot_20230315_115930](https://user-images.githubusercontent.com/56346771/225289721-77d48589-e101-4bc1-9ac5-53f39c21b833.png)

2023-03-15 11:23 UTC, imperosol commented on core/static/user/login.scss
> +  margin: 0;
```suggestion
#page #content {
  display: flex;
  flex-direction: column;
  padding: 10px;
  box-shadow: none;
  background-color: white;
  margin: 0;
```

2023-03-15 11:23 UTC, imperosol commented on core/static/user/login.scss
> +
```suggestion
  > form {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
    max-width: 500px;
    margin-top: 20px;

```

2023-03-15 11:23 UTC, imperosol commented on core/static/user/login.scss
> +      margin: 0;
```suggestion
    > div {
      display: flex;
      flex-direction: column;
      align-items: center;
      width: 100%;
      margin: 0;
```

2023-03-15 11:23 UTC, imperosol commented on core/templates/core/login.jinja
> +            <p class="alert-red">{% trans %}Your username and password didn't match. Please try again.{% endtrans %}</p>
```suggestion
            <p class="alert alert-red">{% trans %}Your username and password didn't match. Please try again.{% endtrans %}</p>
```

2023-03-15 12:22 UTC, imperosol commented
> > Problème d'espacement sur le header des utilisateurs non-authentifiés : ![Screenshot_20230315_115930](https://user-images.githubusercontent.com/56346771/225289721-77d48589-e101-4bc1-9ac5-53f39c21b833.png)
> 
> T'es sûr qu'il te manque pas un truc dans ton build ? j'arrive pas à reproduire ton problème

J'ai fait un `git reset --hard origin/tinople/css-rewrite-taiste` pour être sûr, mais j'ai toujours le même problème.

2023-03-15 12:24 UTC, Juknum commented
> > > Problème d'espacement sur le header des utilisateurs non-authentifiés : ![Screenshot_20230315_115930](https://user-images.githubusercontent.com/56346771/225289721-77d48589-e101-4bc1-9ac5-53f39c21b833.png)
> > 
> > 
> > T'es sûr qu'il te manque pas un truc dans ton build ? j'arrive pas à reproduire ton problème
> 
> J'ai fait un `git reset --hard origin/tinople/css-rewrite-taiste` pour être sûr, mais j'ai toujours le même problème.

Normalement y'a du `padding: 5px 20px;` autour, check voir si la propriété a pas disparue / été remplacée par une de tes modifs

2023-03-15 12:28 UTC, imperosol commented
> > J'ai fait un `git reset --hard origin/tinople/css-rewrite-taiste` pour être sûr, mais j'ai toujours le même problème.
> 
> Normalement y'a du `padding: 5px 20px;` autour, check voir si la propriété a pas disparue / été remplacée par une de tes modifs

Le padding est toujours là.

2023-03-30 12:21 UTC, TheoDurr approved these changes

2023-03-30 12:38 UTC, merged