[PARTENARIAT] Ajout vitrine d'achat billets eurockéennes 2023
ae-utbm/sith3 pull request #582
Opened 2023-03-08 19:12 UTC by Juknum

En attente de validation de la part de Thibault Chausson (respo partenariat)

2023-03-08 19:15 UTC, TheoDurr commented
Possible d'avoir un screen du résultat ?

2023-03-08 19:16 UTC, Juknum commented
> Possible d'avoir un screen du résultat ?

J'ai ajouté les screens, sinon ils sont dispo dans le salon #informatique du discord AE

2023-03-08 19:31 UTC, imperosol commented on locale/fr/LC_MESSAGES/django.po
> +msgstr "Vous devez être cotisant pour pouvoir accéder à la billetterie des Eurockéennes."
```suggestion
msgid "You must be a member of the AE to access the Eurockéennes ticketing service."
msgstr "Vous devez être cotisant de l'AE pour pouvoir accéder à la billetterie des Eurockéennes."
```
"contributor" a plus le sens d'un donneur sans réelle contrepartie que d'une personne qui est à jour dans ses paiements pour faire partie de l'asso.

2023-03-08 19:32 UTC, TheoDurr commented on locale/fr/LC_MESSAGES/django.po
> +msgstr "Vous devez être cotisant pour pouvoir accéder à la billetterie des Eurockéennes."
Il faut mettre "subscriber" tout comme c'est écrit partout ailleurs pour rester cohérent

2023-03-08 19:34 UTC, TheoDurr requested changes

2023-03-08 19:34 UTC, TheoDurr commented on locale/fr/LC_MESSAGES/django.po
> +msgid "You must be a contributor to access the Eurockéennes ticketing service."
```suggestion
msgid "You must be a subscriber to access the Eurockéennes ticketing service."
```

2023-03-08 19:37 UTC, imperosol approved these changes

2023-03-08 19:38 UTC, TheoDurr approved these changes

2023-03-08 19:39 UTC, TheoDurr commented
Ok pour déploiement, penser à déployer aussi ça sur `taiste` @Juknum une fois validé.

2023-03-08 19:40 UTC, imperosol commented
Et squash les commits avant de merge, aussi

2023-03-09 16:13 UTC, TheoDurr approved these changes

2023-03-09 16:13 UTC, merged