Repair NaN bug for autocomplete on counter click
ae-utbm/sith3 pull request #583
Opened 2023-03-09 13:22 UTC by imperosol

Ca résoud le problème de l'autocomplétion cassée sur les comptoirs.

2023-03-09 20:37 UTC, Juknum commented on counter/static/counter/js/counter_click.js
> +    // let search = "";
```suggestion
```

2023-03-09 20:40 UTC, Juknum requested changes

2023-03-09 20:40 UTC, Juknum commented on counter/static/counter/js/counter_click.js
> +    // let search = "";
```suggestion
```

Inutile de garder du code commenté

2023-03-09 21:30 UTC, imperosol commented on counter/static/counter/js/counter_click.js
> +    // let search = "";
en effet

2023-03-10 09:48 UTC, Juknum approved these changes

2023-03-10 09:49 UTC, merged