[FIX] Correction de bugs relevés par Sentry
ae-utbm/sith3 pull request #617
Opened 2023-04-05 14:29 UTC by Juknum

### Fixes
- #600 : Ajout des mêmes étapes de vérification que dans `trombi/views.py#335`

2023-04-08 12:19 UTC, imperosol submitted a review, later dismissed
Il manque les tests de régression.

2023-04-08 12:19 UTC, imperosol commented on core/models.py
> +                if not c:
```suggestion
                if c is None:
```

2023-04-08 12:19 UTC, imperosol commented on core/views/files.py
> +        return forbidden(request, _("You are not allowed to view this file"))
C'était très bien comme c'était. Changer ça, ça rend le code moins maintenable.

2023-04-08 12:19 UTC, imperosol commented on core/views/files.py
> +        return not_found(request, _("File not found"))
```suggestion
        raise Http404
```
Faut aussi faire l'import, si c'est pas fait.

2023-04-08 12:19 UTC, imperosol commented on core/views/site.py
> +
```suggestion
    def get_queryset(self) -> QuerySet[Notification]:
        if self.request.user.is_anonymous:
            return Notification.objects.none()
```

2023-04-08 12:19 UTC, imperosol commented on locale/fr/LC_MESSAGES/django.po
> +
Ces traductions ne sont pas utiles (cf. commentaires plus haut)

2023-04-08 12:47 UTC, Juknum commented on core/views/files.py
> +        return forbidden(request, _("You are not allowed to view this file"))
Certes, mais ça avait au moins le mérite de ramener l'utilisateur sur la page de connexion en lui indiquant qu'il n'avait pas les permissions d'accès au fichier

2023-04-08 12:49 UTC, Juknum commented
> Il manque les tests de régression.

Il peut manquer ce que tu veux, c'est un draft ça porte bien son nom mdrr

2023-04-08 14:01 UTC, imperosol commented on core/views/files.py
> +        return forbidden(request, _("You are not allowed to view this file"))
C'est déjà le comportement qu'il y avait.

Si jamais tu voulais vraiment personnaliser le message, chez moi je ne le vois pas.

2023-04-13 17:04 UTC, Juknum commented
@Hyask @klmp200 

J'ai atteint le max d'issue qu'on peut associer sur une PR (genre y'a un max mdr) du coup j'aurais besoin de vos reviews & de vos connaissances pour savoir si les bugs que j'ai corrigé là bah ils le sont vraiment :eyes:

2023-04-14 16:16 UTC, Hyask commented
@Juknum Je n'ai pas pris le temps de rouvrir en détail chaque issue, mais avec ton résumé et les changements de code proposés, c'est sûr qu'au moins une bonne partie des bugs seront effectivement corrigés. Dans tous les cas, tes changements semble biens, donc le mieux, c'est probablement de les prendre, et au pire, bah faudra juste refaire des corrections.

GG o7

2023-04-14 16:16 UTC, Hyask submitted a review, later dismissed

2023-04-14 17:09 UTC, imperosol requested changes
La plupart des bugs ont l'air d'avoir été résolus, mais c'est dur à dire. La plupart des erreurs sont décrites en une lignes, donc pour certaines, je ne vois même pas en quoi elles consistent.

Les personnes qui laissent leur revue sur cette PR n'ont pas passé les derniers jours la tête dans le code comme tu l'as fait. On peut faire autant de revues qu'on veut, ça ne remplacera jamais une suite de tests. Une revue de code, ça peut passer à côté des cas particuliers, ça n'est pas complètement fiable et surtout ça ne donne aucune garantie que le bug ne sera pas réintroduit plus tard dans le processus de développement.
J'insiste vraiment la-dessus : il faut des tests.

2023-04-15 12:32 UTC, Juknum commented on core/views/files.py
> +        return not_found(request, _("File not found"))
Parce que c'est le fichier qui n'est pas trouvé, pas la page, donc autant retourner la page 404 avec l'erreur que juste l'erreur 404. De plus, c'est à mon sens plus propre de faire un return qu'un raise.

2023-04-15 12:34 UTC, Juknum commented on club/models.py
> +
C'est pour corriger : 
- #627 

Ca permet de remplacer l'ancien nom dans les groupes d'accès par le nouveau.

2023-04-15 12:35 UTC, Juknum commented on core/models.py
>                  User._club_memberships[name] = mem
Bah normal non ? s'il existe pas une fois il existera pas la fois d'après ? tu proposerais quoi ?

2023-04-15 12:42 UTC, Juknum commented on trombi/views.py
> +            request.user.is_anonymous
C'était pas le but de la correction, ici le problème c'est que même les gens anonymes étaient checké pour savoir s'ils avaient ou non un trombi.

2023-04-15 12:45 UTC, Juknum commented on core/views/user.py
> +
Pareil qu'au dessus, les utilisateurs anonymes

2023-04-15 13:45 UTC, imperosol commented on core/models.py
>                  User._club_memberships[name] = mem
Justement, s'il n'existe pas non plus la fois d'après, c'est qu'il faut utiliser l'espèce de cache qui est utilisée dans la fonction, avec le dictionnaire `_club_memberships`. Comme ça, le nom du club est associé à `None` et quand on repasse dans la fonction, `mem` vaut directement `None` et la condition `if mem` échoue, ce qui fait que la fonction renverra à nouveau `False`, mais sans avoir à refaire de requête.

2023-04-15 13:56 UTC, imperosol commented on core/views/files.py
> +        return not_found(request, _("File not found"))
Pas dans le sens de Django, parce que :

- 404, ça n'indique pas une page non trouvée, mais une ressource de manière générale, donc ici le 404 est pertinent.
- Tu peux vérifier, le message que tu précises dans l'appel de ta fonction n’apparaît pas sur la page 404.
- Quand une erreur Http404 est levée, Django prend automatiquement en charge le routage : quand le projet est en mode DEBUG, on obtient une page avec la pile d'appels et une description de l'erreur et quand il n'est pas en mode DEBUG, ça appelle la vue not_found(). Bref, ça fait exactement ce que tu fais, mais en mieux, parce que plus facile à débuguer et plus idiomatique.

Tu peux vérifier, il n'y a aucun appel en clair à la vue not_found dans le projet, c'est que du raise Http404.

2023-04-15 14:04 UTC, imperosol commented on trombi/views.py
> +            request.user.is_anonymous
Oui, mais c'est pas terrible que la correction amène à renvoyer quelque chose d'incorrect.
Il aurait fallu rajouter une condition au-dessus qui renvoie un 403 plutôt que d'incorporer ça à la condition qui renvoie un 404.

Soit : 
```py
if request.user.is_anonymous:
    raise PermissionDenied
if (
    self.object.trombi.id != request.user.trombi_user.trombi.id
    or self.object.user.id == request.user.id
    or not self.object.trombi.show_profiles
):
    raise Http404
```

2023-04-15 14:06 UTC, imperosol commented on core/views/user.py
> +
Dans ce cas, pareil qu'en dessous, fais une autre condition au dessus plutôt que d'incorporer ça à la condition qui renvoie un 404. Ca rend tes intentions beaucoup plus claires.

2023-04-20 12:20 UTC, Juknum commented on core/models.py
>                  User._club_memberships[name] = mem
J'ai aucune idée de comment faire ça :/

2023-05-02 11:07 UTC, merged

2023-05-02 11:55 UTC, imperosol commented
Les tests n'ont pas été écrits. C'est pas la première fois que ça arrive. Il faut écrire les tests. Vraiment, j'insiste.

Tu as fait ça uniquement par flemme. Tu utilises Github Copilot, pourtant, et Copilot est assez bon pour écrire des tests ; des tests simples, de surcroît.

La couverture en tests du projet est déjà mauvaise. La laisser diminuer, c'est un comportement de merde qui contribue à l'instabilité de la base de code. Il n'y a aucune raison valable pour ne pas avoir écrit ces tests. Cette omission, c'est de la bêtise et de l'inconsidération à l'état pur.