add missing method on AnonymousUser
ae-utbm/sith3 pull request #649
Opened 2023-05-12 20:03 UTC by imperosol

Repair [this](https://sentry.ae.utbm.fr/organizations/ae-utbm/issues/158/?referrer=webhooks_plugin).

This view call User.is_com_admin for right checking. However, the AnonymousUser did not have such a method. This PR adds it.

This also adds some tests to avoid regression.

2023-09-06 09:42 UTC, Juknum requested changes

2023-09-06 09:42 UTC, Juknum commented on com/tests.py
> +        # by default a new isn't moderated
```suggestion
        # by default a news isn't moderated
```

2023-09-06 09:43 UTC, Juknum commented
@imperosol tu pourrais check dans les issues sur GitHub si cette PR peut en fix et les mettre en référence ? thx

2023-09-07 20:45 UTC, imperosol commented
> @imperosol tu pourrais check dans les issues sur GitHub si cette PR peut en fix et les mettre en référence ? thx

Sentry n'a pas créé d'issue github pour ce problème-là.

2023-09-07 21:53 UTC, Juknum approved these changes

2023-09-07 21:53 UTC, merged