Xapian from sources and fix CVE
ae-utbm/sith3 pull request #679
Opened 2024-06-22 19:19 UTC by klmp200

Xapian is a pain, I try to address that

Also, a minor django upgrade breaks multi file upload, it's fixed here

2024-06-22 22:07 UTC, imperosol requested changes
C'est toujours un peu chiant de gérer xapian, mais c'est déjà pas mal mieux que ce qu'on faisait avec xapian-bindings.

2024-06-22 22:07 UTC, imperosol commented on core/views/files.py
> +class MultipleFileField(forms.FileField):
Django implémente une classe différente pour `ImageField` pour les images, donc , pour quand on veut un form field pour gérer plusieurs images, ça peut être mieux de créer une autre classe `MultipleImageField`

2024-06-23 18:59 UTC, klmp200 commented on pyproject.toml
> +python = "^3.10,<3.12"
C'est pour mistune que j'ai restreint la version.
Ça m'a sorti des warnings et j'ai voulu éviter les risques de casse.

2024-06-23 19:00 UTC, klmp200 commented on core/views/files.py
> +class MultipleFileField(forms.FileField):
C'est vrai. Mais j'ai gardé (j'espère) exactement le même comportement qu'avant.
Ça peut être bien de se pencher là dessus dans le futur.

@Hyask il y a une raison pour laquelle t'as pas utilisé le ImageField ?

2024-06-23 19:01 UTC, klmp200 commented on core/management/commands/install_xapian.sh
> +fi
Il est vrai, je vais régler ça :)

2024-06-23 19:14 UTC, klmp200 commented
Il semblerait que certains tests ne passent pas
Je ne sais pas si c'est moi qui les ai introduit, je vais faire des tests en local

2024-06-24 06:38 UTC, imperosol commented on pyproject.toml
> +python = "^3.10,<3.12"
Mets un commentaire à côté pour dire que c'est à cause de ça, histoire qu'on pense bien à retirer le`<3.12` quand on fera la màj de mistune.

2024-06-24 06:53 UTC, imperosol commented on core/views/files.py
> +class MultipleFileField(forms.FileField):
> @Hyask il y a une raison pour laquelle t'as pas utilisé le ImageField ?

Il a utilisé `ImageField` (même que tu l'as modifié), dans sas/views.py, L.43.

`ImageField` de `FileField`. Les deux utilisent le même widget (`FileInput`), donc ça donne la même chose sur le front, mais côté back, `ImageField` rajoute des vérifications en plus (et les messages d'erreur qui vont avec), du genre vérifier que le fichier a une extension valide (jpeg, png, gif...) ou vérifier que le fichier n'est pas tronqué ou corrompu.

Voir directement le code, qui est pas très long (la classe FileField est juste au-dessus) : https://github.com/django/django/blob/7ba2a0db20c37a5b1500434ca4ed48022311c171/django/forms/fields.py#L706

2024-06-24 07:23 UTC, imperosol commented on core/views/files.py
> +        widget=MultipleFileInput(),
Bro, t'as créé une classe MultipleFileField, faut l'utiliser :
```python
file_field = MultipleFileField(label=_("Files"), required=False)

2024-06-24 08:33 UTC, klmp200 commented on core/views/files.py
> +        widget=MultipleFileInput(),
Ah mais oui ! J'avais pas vu que ça avait sauté ! J'avais mis ça mais en réarangeant mes commits c'est parti !

2024-06-24 08:34 UTC, klmp200 commented on core/views/files.py
> +        widget=MultipleFileInput(),
Ah mais je l'ai utilisé n'importe comment là !

2024-06-24 08:40 UTC, klmp200 commented on core/views/files.py
> +class MultipleFileField(forms.FileField):
Oulala, mais t'as raison en plus !
J'étais vraiment cramé quand j'ai écrit ça !
Merci

2024-06-24 10:03 UTC, imperosol approved these changes

2024-06-24 11:37 UTC, imperosol submitted a review, later dismissed

2024-06-25 18:29 UTC, Juknum approved these changes

2024-06-25 18:41 UTC, Juknum commented
C'est good pour toi @Hyask et on merge ?

2024-06-26 07:40 UTC, Hyask requested changes
Juste un commentaire sur le script shell, sinon le reste a l'air OK.

2024-06-26 07:40 UTC, Hyask commented on core/management/commands/install_xapian.sh
> +rm -rf $VIRTUAL_ENV/packages
```suggestion
rm -rf "$VIRTUAL_ENV/packages"
```
`shellcheck` se plaint là, et à plein d'autres endroits aussi. Ça serait mieux, au cas où ton `VIRTUAL_ENV` contienne des espaces ou autre caractère louche.

2024-06-26 09:26 UTC, klmp200 commented on core/management/commands/install_xapian.sh
> +rm -rf $VIRTUAL_ENV/packages
Je conaissaisp pas le tool, je l'ai mis dans mon éditeur
Je corrige tout ça :)

2024-06-26 09:33 UTC, Hyask commented on core/management/commands/install_xapian.sh
> +rm -rf $VIRTUAL_ENV/packages
Nice :-)

2024-06-26 09:34 UTC, Hyask approved these changes

2024-06-26 09:37 UTC, imperosol approved these changes

2024-06-26 09:48 UTC, merged