Use pre-commits hooks instead of ruff directly
ae-utbm/sith3 pull request #683
Opened 2024-06-26 17:13 UTC by klmp200

Pour plus d'unification et prévoir l'ajout de plus de tools pour check la qualité, j'ai mis des pre-commits et mis ruff dedans

2024-06-26 17:15 UTC, Juknum commented
Ça marche sous n'importe quel OS ?

2024-06-26 17:19 UTC, klmp200 commented
> Ça marche sous n'importe quel OS ?

Oui, ça utilise la fonctionnalité de hooks de git.
Le projet pre-commit c'est un projet python qui permet de contrôler les fichiers de config de git pour le projet de manière simple à partir d'un fichier yaml.

Ça fonctionne sur mac, windows, linux, bsd, n'importe où tant qu'on peut faire tourner git et python. Et que ce que tu met dans tes pre-commits est compatible avec ton os bien évidement.

2024-06-26 17:21 UTC, Juknum commented
> Oui, ça utilise la fonctionnalité de hooks de git. Le projet pre-commit c'est un projet python qui permet de contrôler les fichiers de config de git pour le projet de manière simple à partir d'un fichier yaml.
> 
> Ça fonctionne sur mac, windows, linux, bsd, n'importe où tant qu'on peut faire tourner git et python. Et que ce que tu met dans tes pre-commits est compatible avec ton os bien évidement.

Nice parce qu'on j'avais déjà utilisé d'autres outils du genre et ça marchait que sous Linux/MacOS :/

2024-06-26 17:22 UTC, klmp200 commented
> > Oui, ça utilise la fonctionnalité de hooks de git. Le projet pre-commit c'est un projet python qui permet de contrôler les fichiers de config de git pour le projet de manière simple à partir d'un fichier yaml.
> > Ça fonctionne sur mac, windows, linux, bsd, n'importe où tant qu'on peut faire tourner git et python. Et que ce que tu met dans tes pre-commits est compatible avec ton os bien évidement.
> 
> Nice parce que j'avais déjà utilisé d'autres outils du genre et ça marchait que sous Linux/MacOS :/

Pour certain je l'utilise sur windows en natif au travail (pas de wsl)

2024-06-26 17:27 UTC, Juknum approved these changes

2024-06-26 17:37 UTC, klmp200 commented
Ci testée. Quand on n'applique pas les pre-commits, ça ressemble à ça
![image](https://github.com/ae-utbm/sith3/assets/5844862/d42ca654-4480-490c-a7ce-18cc32b9ede0)

2024-06-27 07:41 UTC, imperosol requested changes
Il manque surtout pre-commit dans les dépendances du projet et les instructions pour mettre en place le pre-commit.

2024-06-27 07:41 UTC, imperosol commented on pyproject.toml
> +extend-select = ["I"]
Y a pas besoin du `extend-select`, vu qu'il y a déjà le select.

`extend-select`, c'est pour quand tu veux avoir une configuration propre à un répertoire du projet ou que tu veux rajouter des règles en ligne de commande.

2024-06-27 07:41 UTC, imperosol commented on .github/workflows/ci.yml
> +    - uses: actions/setup-python@v3
```suggestion
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
```

2024-06-27 07:41 UTC, imperosol commented on doc/start/devtools.rst
> +Une fois installé comme indiqué dans la documentation, il suffit de commit et tout est automatique.
Tu expliques à quoi sert pre-commit, mais tu n'expliques pas comment l'installer ni comment le configurer.

2024-06-27 07:41 UTC, imperosol commented on doc/start/devtools.rst
> +Pour installer les pre-commits hoosk, nous utilisons le logiciel [pre-commit](https://pre-commit.com/) pour simplifier leur gestion.
```suggestion
Pour installer les pre-commits hooks, nous utilisons le logiciel [pre-commit](https://pre-commit.com/) pour simplifier leur gestion.
```

2024-06-28 07:02 UTC, imperosol requested changes

2024-06-28 07:02 UTC, imperosol commented on doc/start/devtools.rst
> +C'est très pratique pour ne pas oublier de formater le code et autre.
```suggestion
La procédure habituelle pour contribuer au projet consiste à commit des modifications, puis à les push sur le dépôt distant et à ouvrir une pull request. Cette PR va faire tourner les outils de vérification de la qualité de code. Si la vérification échoue, la PR est bloquée, et il faut réparer le problème (ce qui implique de push un micro-commit ou de push force sur la branche).

Dans l'idéal, on aimerait donc qu'il soit impossible d'oublier de faire tourner ces vérification. Pour ça, il existe un mécanisme : les pre-commits hooks. Ce sont des actions qui tournent automatiquement lorsque vous effectuez un `git commit`. Ces dernières vont analyser et éventuellement modifier le code, avant que Git n'ajoute effectivement le commit sur l'arbre git. Voyez ça comme une micro-CI qui tourne en local.

Les git hooks sont une fonctionnalité par défaut de Git. Cependant, leur configuration peut-être un peu embêtante si vous le faites manuellement. Pour gérer ça plus simplement, nous utilisons le logiciel python [pre-commit](https://pre-commit.com/) qui permet de contrôler leur installation via un seul fichier de configuration, placé à la racine du projet (plus précisément, il s'agit du fichier `.pre-commit-config.yaml`).

.. note::

    Les pre-commits sont également utilisés dans la CI. Si ces derniers fonctionnent localement, vous avez la garantie que la pipeline ne sera pas fachée. ;)
```

2024-06-28 07:51 UTC, klmp200 commented on .pre-commit-config.yaml
> +      - id: ruff-format
Dans la CI c'est pas un soucis
J'utilise une fonctionnalité de pre-commit qui renvoie un code d'erreur si les fichiers diffères et qui montre les différences.
La pipeline s'arrête sur une erreur et on peut voir le diff.

2024-06-28 08:06 UTC, imperosol commented on .pre-commit-config.yaml
> +      - id: ruff-format
Mais dans ce cas, ça pose pas de problème en local ?
Parce que justement, on veut que le format se fasse automatiquement en local, mais pas en distant.

2024-06-28 08:23 UTC, klmp200 commented on .pre-commit-config.yaml
> +      - id: ruff-format
C'est le `--show-diff-on-failure` de la ci qui fait ça.
Tant que tu l'appelle pas en local c'est pas un soucis :)

2024-07-01 12:06 UTC, imperosol commented on .pre-commit-config.yaml
> +      - id: ruff-format
Comme les règles non fixables de `ruff check` ne créent pas de diff, il se passe quoi pour ça ?

2024-07-01 19:26 UTC, klmp200 commented on .pre-commit-config.yaml
> +      - id: ruff-format
Ben ça stoppe avec l'erreur que t'aurais en faisant tourner ça en local.
Dans tous les cas la pipeline se termine

2024-07-02 07:00 UTC, imperosol commented on .pre-commit-config.yaml
> +      - id: ruff-format
J'ai essayé d'introduire une erreur Ruff non-fixable et une autre fixable et de faire tourner `pre-commit run --all-files --show-diff-on-failure`. Et il y a deux problèmes :
- ça ne stoppe pas avec l'erreur. Le pre-commit fait bien des modification sur les fichier, même avec le flag `--show-diff-on-failure`. Tout ce que ça change, c'est que ça affiche le diff de la branche
- Quand je dit le diff, c'est l'intégralité du diff, y compris les modifications qui n'ont pas été faites par Ruff. Donc le résultat de la CI est pas super lisible.

2024-07-03 06:40 UTC, imperosol approved these changes
Ca me parait bien

2024-07-03 08:04 UTC, merged