Fix forum topic creation error
ae-utbm/sith3 pull request #709
Opened 2024-07-09 14:56 UTC by klmp200

2024-07-09 15:07 UTC, Hyask submitted a review, later dismissed
Génial, un premier test du forum! J'avais pas eu le temps, dans le bus, on était arrivé au Ski'UT trop vite :-)

2024-07-09 15:10 UTC, imperosol requested changes

2024-07-10 08:48 UTC, imperosol commented on forum/tests.py
> +        assert not ForumTopic.objects.filter(_title=payload["title"]).first()
```suggestion
        assert not ForumTopic.objects.filter(_title=payload["title"]).exists()
```

2024-07-10 08:48 UTC, imperosol commented on forum/tests.py
> +        )
Plusieurs choses que je me dis en voyant ça :
- l'url de redirection n'est pas logique. Quand on crée un topic, ça devrait rediriger vers le topic, pas vers un message du topic.
- Mauvaise logique de sélection du message. Le fait que l'id soit égal au nombre de messages est juste un accident. Si on supprime un message, ça n'est plus vrai. Si on ne commence pas à l'id 1, ça n'est plus vrai non plus. La sélection devrait plutôt se faire avec un `ForumMessage.objects.order_by("date").last()`

2024-07-10 08:50 UTC, imperosol commented
Et aussi, ça donne quoi, les tests, avec un autre utilisateur que root ?

2024-07-10 08:53 UTC, klmp200 commented on forum/tests.py
> +        )
En fait, techniquement, ça te renvoi au message que tu viens de créer.
Le problème ici c'est que créer un topic c'est créer un message ET un topic en même temps

2024-07-10 08:54 UTC, klmp200 commented
> Et aussi, ça donne quoi, les tests, avec un autre utilisateur que root ?

Ça plante parce que les droits dans le forum généré par populate sont pas set correctement

Là le but c'était juste de mettre un test rapide pour juste voir si on a rien pété en général, je veux pas trop figer la logique du truc, histoire qu'on ai le champ libre pour améliorer le forum sans être gêné par les tests

2024-07-10 09:03 UTC, klmp200 commented
> > Ça plante parce que les droits dans le forum généré par populate sont pas set correctement
> > Là le but c'était juste de mettre un test rapide pour juste voir si on a rien pété en général, je veux pas trop figer la logique du truc, histoire qu'on ai le champ libre pour améliorer le forum sans être gêné par les tests
> 
> Ca plante comment ?

Ça te dit que t'as pas le droit, tout simplement.

2024-07-10 09:04 UTC, imperosol commented
> Ça te dit que t'as pas le droit, tout simplement.

Feature, not a bug.
Autant le rajouter. Si jamais on veut changer le fonctionnement du forum, il y aura juste à supprimer et réécrire certains tests.

2024-07-10 09:19 UTC, imperosol commented on forum/tests.py
> +        )
> En fait, techniquement, ça te renvoi au message que tu viens de créer. Le problème ici c'est que créer un topic c'est créer un message ET un topic en même temps

Certes. Ca serait un peu chiant à modifier, donc tant pis pour ça, on verra plus tard.
Par contre, il reste la requête pour sélectionner le message.

2024-07-11 10:01 UTC, imperosol approved these changes

2024-07-11 10:05 UTC, imperosol commented
Avec le dernier déploiement, on devrait avoir un poil plus de protection contre les bots.
Donc c'est bon pour moi si on répare juste l'envoi des messages.

Evnetuellement, on peut quand même rajouter une PR pour empêcher strictement tout accès au groupe Public (qui pour l'instant à droit de voir pas mal de topics). Comme ça on est sûr de bloquer complètement tout ce qui n'a pas réussi à se connecter.

2024-07-11 11:23 UTC, merged