Small refactor for counters
ae-utbm/sith3 pull request #720
Opened 2024-07-18 14:29 UTC by imperosol

Quelques refactors qui permettent d'optimiser certaines requêtes db, de mieux utiliser la cached_property `Counter.barmen_list` et d'alléger un peu les vues pour la connexion et la déconnexion des barmen

2024-07-18 16:46 UTC, Hyask reviewed
À part cette question, ça semble bon. Joli travail.

2024-07-18 16:46 UTC, Hyask commented on counter/models.py
> +        perms.filter(activity__lte=timeout).update(end=F("activity"))
J'ai l'impression qu'il manque le fait d'enlever les barmen qu'on vient de déconnecter de la liste, ou alors j'ai raté un truc? Y'a pas de cache sur la queryset après un truc comme ça? Le `select_related()` qui suit va bien renvoyer les bonnes données?

2024-07-18 17:09 UTC, imperosol commented on counter/models.py
> +        perms.filter(activity__lte=timeout).update(end=F("activity"))
Les querysets qui retournent d'autre queryset sont lazy par défaut.
Donc :
```python
perms = self.permanencies.filter(end=None)  # on construit une requête, mais on n'envoie rien
# ...
perms.filter(activity__lte=timeout).update(end=F("activity"))  # là on envoie une vraie requête DB
return [p.user for p in perms.select_related("user")]  # et là on envoie une autre requête db
```
Comme la deuxième requête arrive après celle qui a déconnecté tous les barmens qui sont timeout, on sait qu'il ne reste en db que des utilisateurs qui ne sont pas timeout.

2024-07-18 17:22 UTC, Hyask commented on counter/models.py
> +        perms.filter(activity__lte=timeout).update(end=F("activity"))
Ça fait sense.

2024-07-18 17:23 UTC, Hyask approved these changes

2024-07-19 14:08 UTC, klmp200 requested changes
Ça fait vraiment du bien comme refactor :)

2024-07-19 14:08 UTC, klmp200 commented on counter/models.py
> +        return any(ae.get_membership_for(barman) for barman in self.barmen_list)
```suggestion
        return any(ae.get_membership_for(barmen) for barmen in self.barmen_list)
```

2024-07-19 14:08 UTC, klmp200 commented on counter/views.py
> +def counter_login(request: HttpRequest, counter_id: int) -> HttpResponseRedirect:
Petite docstring ?

2024-07-19 14:08 UTC, klmp200 commented on counter/views.py
> +def counter_logout(request: HttpRequest, counter_id: int) -> HttpResponseRedirect:
Petite doctsring aussi ? :)

2024-07-19 14:10 UTC, imperosol commented on counter/models.py
> +        return any(ae.get_membership_for(barman) for barman in self.barmen_list)
`barman`, c'est du singulier ; `barmen`, c'est du pluriel.
On examine un barman à la fois, donc c'est du singulier.

2024-07-20 22:46 UTC, klmp200 commented on counter/models.py
> +        return any(ae.get_membership_for(barman) for barman in self.barmen_list)
Fair enough

2024-07-20 22:47 UTC, klmp200 submitted a review, later dismissed

2024-07-21 08:50 UTC, imperosol commented
rebase

2024-07-21 09:15 UTC, klmp200 approved these changes

2024-07-21 13:39 UTC, merged