introduce djhtml as jinja+scss formater
ae-utbm/sith3 pull request #734
Opened 2024-07-24 17:40 UTC by imperosol

On avait une formateur pour le Python, mais pas pour le reste.
Avec djHTML, on peut formatter automatiquement le SCSS et le Jinja.
C'est fait en Python, et il y a un pre-commit, donc ça s'intègre très bien au projet et à la CI.

Et au passage, on formatte.

2024-07-24 20:29 UTC, klmp200 requested changes
J'ai pas lu en détail les fichiers formatés et je pense que ce serait futile

2024-07-24 20:29 UTC, klmp200 commented on pyproject.toml
> +djhtml = "^3.0.6"
Ça va dans les dev dépendances ça

2024-07-24 20:34 UTC, imperosol commented on pyproject.toml
> +djhtml = "^3.0.6"
my bad, oui

2024-07-25 13:49 UTC, imperosol commented on pyproject.toml
> +djhtml = "^3.0.6"
Corrigé

2024-07-25 14:04 UTC, imperosol commented
rebase

2024-07-25 14:21 UTC, klmp200 commented on core/templates/core/user_pictures.jinja
> +              JSZipUtils.getBinaryContent(picture.full_size_url, (err, data) =>{
C'est un peu bizarre ça

2024-07-25 14:23 UTC, klmp200 commented on core/templates/core/user_pictures.jinja
> +          .on("data", (
C'est un peu dégueu ça aussi, non ?

2024-07-25 14:40 UTC, klmp200 approved these changes

2024-07-25 14:46 UTC, merged