Eboutic big refactor
ae-utbm/sith3 pull request #742
Opened 2024-07-27 22:56 UTC by imperosol

J'ai profité des dernières fonctionnalités qu'on a ajouté au site pour revenir sur l'eboutic.
Pas de changement de visuel, mais quelques améliorations dans le back et dans le JS :

- En utilisant Pydantic, on peut simplifier beaucoup la logique de la validation du panier, tout en ayant des perfs suffisantes pour que même un json profondément imbriqué soit rapide à parser (c'était pour ça qu'on avait mis ce regex un peu horrible, à la base)
- Les routes de gestion des données Paybox et des données de facturation ont été placées dans des contrôleurs d'API.
- J'ai trouvé un moyen de faire la vérification des droits des produits de l'eboutic en deux requêtes seulement. Ca va faire économiser une quinzaine de requêtes en moyenne sur le chargement de l'eboutic, ce qui peut représenter une trentaine de millisecondes.
- Egalement, la construction du panier en db demande moins de requêtes. Comme ce sont essentiellement des opérations en écriture, le gain de performance devrait être significatif.
- Et j'ai réécrit quelques tests.

2024-07-30 13:25 UTC, klmp200 submitted a review, later dismissed
Beaucoup de trucs où je suis pas confiant de review

2024-07-30 13:25 UTC, klmp200 commented on counter/models.py
> +            self.send_mail_customer()
Ça peut crash ça, non ?

2024-07-30 13:25 UTC, klmp200 commented on counter/tests.py
>              "zip_code": "34301",
De mes tests à la main, on peut vraiment mettre n'importe quoi là dedans

2024-07-30 13:25 UTC, klmp200 commented on eboutic/api.py
> +        if user_id == self.context.request.user.id:
On peut pas exprimer ça avec une permission, je pense que ce sera vraiment pas la dernière fois où ça va arriver
Après, j'imagine que t'as pas forcément accès à l'user id au moment du calcul de permission

2024-07-30 13:25 UTC, klmp200 commented on eboutic/views.py
> +                path="/eboutic",
```suggestion
                path="/eboutic",
                signed=True,
```

2024-07-30 13:25 UTC, klmp200 commented on sith/settings.py
> +SITH_EBOUTIC_PBX_SITE = "1999888"
Ça fait quoi de changer ça ?

2024-07-30 19:33 UTC, imperosol commented on sith/settings.py
> +SITH_EBOUTIC_PBX_SITE = "1999888"
Ca fait que les paiements en ligne deviennent testables en local.

2024-07-30 20:58 UTC, imperosol commented on counter/models.py
> +            self.send_mail_customer()
Non, parce que j'ai aussi modifié la fonction pour qu'elle envoie le mail comme ça :
```python
        self.customer.user.email_user(
            subject, message_txt, html_message=message_html, fail_silently=True
        )
```

Et si malgré tout il y a autre chose qui crash, alors je préfère que ça crash. Un mail qui ne part pas, c'est pas critique, mais c'est grave, donc je préfère que ça finisse sur le Sentry plutôt que ça échoue silencieusement.

2024-07-30 20:59 UTC, imperosol commented on counter/tests.py
>              "zip_code": "34301",
Oui, on peut mettre n'importe quoi. On a toujours pu mettre n'importe quoi. Et je crois que la banque en a rien à foutre.

2024-07-30 21:12 UTC, imperosol commented on eboutic/api.py
> +        if user_id == self.context.request.user.id:
Le problème, c'est que ce sont deux niveaux de perm différent : au niveau de la vue, et au niveau de l'objet. Et on cherche à avoir les deux. La permission par objet doit laisser rentrer tout le monde dans la vue, étant donné qu'elle n'est appliquée qu'au moment où on recherche l'objet.

Supposons que la perm pour vérifier que l'user dans l'url est le même que celui qui fait la requête s'appelle `IsSelf`. Alors `IsSelf & IsRoot`, ça équivaut à ne faire rentrer que les root dans la vue et à ne fonctionner que si le root édite son propre profil (c'est pas ce qu'on veut). Et `IsSelf | IsRoot`, ça équivaut à laisser rentrer tout le monde, et à laisser tout le monde éditer le profil de tout le monde (c'est encore pire).

2024-08-07 09:26 UTC, klmp200 requested changes
J'ai des soucis sur la validation des informations de facturation :/
J'ai testé avec guy et c'est impossible de valider mes infos

2024-08-07 09:26 UTC, klmp200 commented on counter/models.py
> +            self.send_mail_customer()
J'ai testé en prod avec vrai et faux email et effectivement ça ne pose pas de problème :)

2024-08-07 09:26 UTC, klmp200 commented on counter/tests.py
>              "zip_code": "34301",
Faudra ptet faire un truc pour ça un jour, mais clairement pas maintenant

2024-08-07 18:25 UTC, klmp200 requested changes

2024-08-07 18:27 UTC, klmp200 submitted a review, later dismissed

2024-08-07 18:36 UTC, klmp200 approved these changes

2024-08-07 18:36 UTC, merged