Ajax image sas
ae-utbm/sith3 pull request #809
Opened 2024-09-03 18:25 UTC by imperosol

Finalisation de l'ajaxification des images.

[screen-recording(3).webm](https://github.com/user-attachments/assets/afabf200-b70a-4f89-94e6-37495d9c3a8e)

2024-09-04 14:21 UTC, klmp200 commented on locale/fr/LC_MESSAGES/djangojs.po
> +# SOME DESCRIPTIVE TITLE.
À update

2024-09-04 14:46 UTC, klmp200 requested changes
Mes tests continuent et ma review est pas terminée

2024-09-04 14:46 UTC, klmp200 commented on core/static/core/select2/select2.min.js
Ça doit pas aller dans le dossier vendored ?

2024-09-04 14:46 UTC, klmp200 commented on sas/static/sas/js/picture.js
viewer.js ce serait pas mieux comme nom ?

2024-09-04 14:46 UTC, klmp200 commented on sas/static/sas/js/picture.js
> +    current_picture: undefined,
Pour éviter pas mal des erreurs qui sont pendant le chargement
Mais faut quand même changer un peu le template
```suggestion
    current_picture: {
        id: null,
        name: gettext("loading"),
        display_name: gettext("loading"),
        compressed_url: window.location.href,
        profile_url: window.location.href,
        full_size_url: window.location.href,
        date: new Date(),
    },
```

2024-09-04 14:51 UTC, imperosol commented on core/static/core/select2/select2.min.js
Si, bien vu

2024-09-04 14:51 UTC, imperosol commented on sas/static/sas/js/picture.js
J'aime bien, `viewer.js`

2024-09-05 11:07 UTC, klmp200 commented on core/static/core/js/sith-select2.js
> +      ? `<img src="${picture_getter(item)}" alt="item.text"/>`
```suggestion
      ? `<img src="${picture_getter(item)}" alt="item.text" onerror="this.src='{{ static('core/img/unknown.jpg') }}'"/>`
```
Un truc comme ça pour gérer les profils qui sont marqués en privés et dont on ne peut pas voir l'image

2024-09-05 11:09 UTC, klmp200 commented on core/static/core/js/sith-select2.js
> +      ? `<img src="${picture_getter(item)}" alt="item.text"/>`
Ou alors, le onerror peut être dans un handler passé en paramètre, histoire de rendre ça plus générique

2024-09-05 13:16 UTC, klmp200 commented on sas/static/sas/js/picture.js
> +        `/sas/picture/${this.current_picture.id}/`,
Ce serait ptet plus safe de générer ça directement dans le backend et l'envoyer dans le json
On peut avoir un truc genre this.current_picture.sas_url

2024-09-05 13:17 UTC, klmp200 commented on sas/static/sas/js/picture.js
> +        `/api/sas/picture/${this.current_picture.id}/moderate`,
Pareil ici aussi

2024-09-05 13:17 UTC, klmp200 commented on sas/static/sas/js/picture.js
> +        await fetch(`/api/sas/picture/${this.current_picture.id}/identified`)
Pareil ici aussi

2024-09-17 08:28 UTC, klmp200 reviewed
À voir si on met un retry, en tout cas c'est beaucoup mieux à l'utilisation

2024-09-17 08:28 UTC, klmp200 commented on sas/static/sas/js/viewer.js
> +  async load_identifications(options) {
```js
async load_identifications(options, retry=5) {
    if (retry <= 0){ /* We stop fetching */
        this.identification_loading = False;
        return;
    }
    ...
   const resp = await fetch(url);
   if (!resp.ok) {
      this.load_identifications(options, retry-1);
   }
   this.identifications = await resp.json();
   this.identifications_loading = false,
}
```

2024-09-17 08:28 UTC, klmp200 commented on sas/static/sas/js/viewer.js
> +  async load_identifications(options) {
Une idée de comment retry

2024-09-17 15:24 UTC, klmp200 commented on sas/static/sas/js/viewer.js
> +  async load_identifications(options) {
Pas obligé de gérer ça, ce serait peut-être une meilleure solution globalement d'utiliser un wrapper dédié bien fait pour faire des retry sur les fetch en général.

2024-09-17 15:25 UTC, klmp200 requested changes

2024-09-17 15:25 UTC, klmp200 commented on core/schemas.py
> +        if len(value) < 4:
Remettre à 2 c'est mieux selon moi
Déjà parce qu'on peut plus chercher sli sur les données de test avec ça, pour moi c'est une régression

2024-09-17 15:25 UTC, klmp200 commented
À part ça, je pense que c'est bon, faut qu'elle sorte cette PR

2024-09-17 16:11 UTC, imperosol commented on sas/static/sas/js/viewer.js
> +  async load_identifications(options) {
Je suis pas convaincu du bienfait d'un retry.
Concrètement, pourquoi la requête peut échouer ? 

- Si c'est un 404, ça veut dire que la photo n'existe pas. Inutile de réessayer.
- Si c'est un 403, c'est pas en réessayant qu'on aura les droits.
- Si c'est un rate-limit, on va juste aggraver le problème

Le cas où je peux le concevoir, c'est pour un timeout. Mais le timeout du site est relativement généreux. Donc si on rajoute des retry, on rallong juste la requête jusqu'à un point où l'utilisateur aura le sentiment que c'est cassé, sans savoir exactement quoi.

Quitte à faire quelque chose, je pense que c'est encore mieux de dire directement ce qui s'est passé de mal, et d'encourager à recharger la page.

2024-09-17 17:39 UTC, klmp200 approved these changes

2024-09-18 13:03 UTC, merged