fix undeletable SAS pictures
ae-utbm/sith3 pull request #819
Opened 2024-09-09 19:41 UTC by imperosol

fix #818

2024-09-09 21:12 UTC, klmp200 requested changes

2024-09-09 21:12 UTC, klmp200 commented on core/models.py
> +            return user.is_board_member
On pourais avoir un profile_of pas board admin MAIS com_admin

2024-09-09 23:16 UTC, imperosol commented on core/models.py
> +            return user.is_board_member
Ce qu'on dit aux gens, c'est : "pour changer votre photo, demandez à un membre du bureau". Donc ça me parait pas spécialement déconnant.

2024-09-09 23:32 UTC, klmp200 commented on core/models.py
> +            return user.is_board_member
Ah, oui, c'est bon, j'y suis
Tu peux mettre un commentaire pour dire que tu check si c'est une photo de profile, c'est pas clair à la lecture comme ça, j'avais pas fait le lien

2024-09-10 20:41 UTC, klmp200 approved these changes

2024-09-10 21:12 UTC, merged