Forum css rework
ae-utbm/sith3 pull request #831
Opened 2024-09-19 16:17 UTC by imperosol

Change le style des message du forum :

![image](https://github.com/user-attachments/assets/3e73d5dd-6aaf-4c90-9923-a2373a2b4b88)

J'ai aussi rajouté des fixtures, histoire d'avoir d'avoir du contenu.

2024-09-23 21:40 UTC, klmp200 requested changes
À part ça, ça a l'air cool

2024-09-23 21:40 UTC, klmp200 commented on core/templates/core/macros.jinja
> +{% macro paginate_jinja(page, nb_pages) %}
Il y a déjà la macro paginate juste en dessous qui est théoriquement un paginate_jinja.
Il y a moyen de fusioner les deux ?

2024-09-23 21:40 UTC, klmp200 commented on forum/templates/forum/reply.jinja
> +
Plus j'en lis des comme ça plus je me dit qu'un forum_base.jinja serait pas déconnant

2024-09-25 12:38 UTC, imperosol commented on forum/templates/forum/reply.jinja
> +
Boarf, ça va, c'est une ligne. Si jamais on fait plus, on pourra étendre.

2024-09-25 12:39 UTC, imperosol commented on core/templates/core/macros.jinja
> +{% macro paginate_jinja(page, nb_pages) %}
J'ai généralisé. Il en reste une qui demanderait plus de travail, mais c'est hors de sujet pour la PR.

2024-09-25 13:00 UTC, klmp200 commented on core/templates/core/macros.jinja
> +{% macro paginate_jinja(page, nb_pages) %}
Pareil pour le css qui va avec, je vois que tu l'a supprimé de partout, ptet le renommer pour montrer qu'il est deprecated et qu'on l'ajoute pas par accident en pensant qu'on en a besoin pour la nouvelle macro

2024-09-25 13:00 UTC, klmp200 requested changes
À part ça, ça m'a l'air pas mal :)

2024-09-27 09:15 UTC, imperosol commented on core/templates/core/macros.jinja
> +{% macro paginate_jinja(page, nb_pages) %}
> Pareil pour le css qui va avec, je vois que tu l'a supprimé de partout, ptet le renommer pour montrer qu'il est deprecated et qu'on l'ajoute pas par accident en pensant qu'on en a besoin pour la nouvelle macro

Pour le css, il est pas déprécié. C'est le css de la nouvelle pagination, justement. Comme j'ai généralisé cette dernière, j'ai déplacé la déclaration du style directement dans le `base.jinja`.

2024-09-30 07:45 UTC, klmp200 approved these changes

2024-09-30 10:13 UTC, merged