Add the new 3DSv2 fields
ae-utbm/sith3 pull request #842
Opened 2024-09-27 09:00 UTC by imperosol

Le Crédit Agricole a demandé une modification des données qu'on lui envoie lors des paiements en ligne.
En plus des informations de facturation qu'on donnait déjà, il faut fournir maintenant également le numéro de téléphone.

On ne peut pas vraiment rajouter le numéro de téléphone depuis le profil utilisateur, parce que : 
- on n'est pas sûr que les gens aient renseigné un numéro de téléphone
- pour ceux qui l'ont fait, on ne peut pas savoir si c'est ce numéro qu'ils ont envie de transmettre à la banque
- dans tous les cas, transmettre ce genre de données personnelles à un tiers sans demander aux utilisateurs, c'est super douteux au niveau RGPD

On rajoute dont un champ dans le formulaire pour rentrer ses informations de facturation.
Pour tous les utilisateurs qui avaient déjà renseigné les autres infos, on affiche à nouveau le formulaire, avec un message spécial pour les avertir que la banque a changé ses règles et qu'ils doivent donc donner leur numéro de téléphone.

2024-09-27 12:49 UTC, klmp200 requested changes
À part ça, j'ai testé et ça a l'air de fonctionner

2024-09-27 12:49 UTC, klmp200 commented on eboutic/schemas.py
> +    phone_number: str
Faudrait vraiment une validation backend pour ça, sinon c'est vraiment n'imp
On peut utiliser ça https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#validator pour rendre ça simple.
Ou sinon on peut utiliser ce que propose pydantic https://docs.pydantic.dev/latest/api/pydantic_extra_types_phone_numbers/

2024-09-27 12:49 UTC, klmp200 commented on counter/tests/test_counter.py
> +    def test_phone_number_format(
Ça manque d'un test avec un numéro idiot et invalide

2024-09-27 12:50 UTC, imperosol commented on eboutic/schemas.py
> +    phone_number: str
On utilise déjà django-phonenumber-field. C'est ce qui est utilisé dans le modèle.

2024-09-28 11:56 UTC, klmp200 requested changes
À part ça c'est nickel

2024-09-28 11:56 UTC, klmp200 commented on pyproject.toml
> +pydantic-extra-types = { git = "https://github.com/pydantic/pydantic-extra-types.git" }
Fix un numéro de commit avec rev="commit".

2024-09-28 15:58 UTC, klmp200 approved these changes

2024-09-28 15:59 UTC, merged