Better install doc
ae-utbm/sith3 pull request #848
Opened 2024-09-30 08:52 UTC by imperosol

Réorganisation des instructions d'installation pour éviter que les gens se tapent une erreur quand ils tentent de lancer la commande `setup`.

J'ai aussi rajouté une ligne pour rappeler aux gens de faire un `apt update`. Parce que je jure que pour l'instant, tous ceux que j'ai vu installer le projet arrivaient pas à le faire à cause de ça.

2024-10-02 20:16 UTC, klmp200 approved these changes

2024-10-02 20:32 UTC, NaNoMelo commented on docs/tutorial/install.md
> +Clonez le projet et installez les dépendances :
Penser à clone directement depuis une console linux/WSL si sous windows

2024-10-02 22:03 UTC, imperosol commented on docs/tutorial/install.md
> +Clonez le projet et installez les dépendances :
En effet.

2024-10-02 22:30 UTC, klmp200 approved these changes

2024-10-02 22:31 UTC, klmp200 requested changes
Mettre le petit commentaire pour le clone sur windows et c'est bon :)

2024-10-03 09:32 UTC, klmp200 approved these changes

2024-10-03 16:32 UTC, merged